### ISSUE TITLE
RDconnetc data lost

### ISSUE THREAD

**Issue by saisaitian** [menchelab/MultiOme#3]
Dear author：
   When I use the code to reanalysis, and I found the realted files about RDconnetc were lost. Could you help me to fix it?

![image](https://user-images.githubusercontent.com/26356557/177022627-c27692e3-1a85-4726-a450-550e09772bd9.png)

**Comment by izepb** [comment]
Hi. Thank you for your interest! The data was queried via RD-Connect platform. Due to its sensitive nature, the access is restricted to validated users (as stated in the description) and we unfortunately do not have rights to distribute them. We however provide detailed querying and filtering parameters so that validated users of the platform can reproduce the analyses. Please refer to 'RD-Connect cohort' subsection in the Methods of [the paper](https://www.nature.com/articles/s41467-021-26674-1), thank you!

**Comment by saisaitian** [comment]
Hi. Thank you for your reply! In fact, I want to use your ieda for my research, so that to promote and cite your paper.  These files were lost, and I could not run it well for gene prioritization in rare disease patients.  Could you help me to fix it? or share the demo data for me to run? In additon, coud you share 'test_rdconnect_ranking_results.RDS' the I would appreciate. I hope I can get your help.
![image](https://user-images.githubusercontent.com/26356557/179873571-e5d37c93-eabf-48e7-a83f-8253f88f7716.png)
![image](https://user-images.githubusercontent.com/26356557/179877281-71a2a993-ea38-47ec-8939-ff64868959bc.png)
